### PR TITLE
build!: move to unbuild

### LINKED ISSUE #28: Bug: bundling fails using `vite build`
First of all, thank you so much for this project! This saved me from having to switch to a different password encryption library when deploying on cloudflare. I am however encountering an issue when trying to bundle `bcrypt-edge` directly into my project using `vite build`. When doing so I get this error message:

```console
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '<path_to_project>/node_modules/bcrypt-edge/' imported from <path_to_project>/.svelte-kit/output/server/chunks/server.js
    at new NodeError (node:internal/errors:399:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:235:9)
    at packageResolve (node:internal/modules/esm/resolve:876:14)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.16.0
```

Simply adding the following to my `vite.config.ts`, which removes `bcrypt-edge` from the bundle, fixes the issue completely:

```ts
export default defineConfig({
    ...
    ssr: {
        noExternal: ['bcrypt-edge']
    }
});
```

In your README you mentioned that bundling this library should not be a problem, so I assume that this is not intended.

Tested versions:
bcrypt-edge: 0.0.6
vite: vite/5.3.5 linux-x64 node-v18.16.0

### PR DESCRIPTION
**Pull request by Barbapapazes**
fix #28 

Hello 👋,

I update the builder to [unbuild](https://github.com/unjs/unbuild). This builder uses Rollup under the hood but with a convenient API and reads the `package.json#exports` field to fails is it does not match the output.

I remove the key `module` since it's just a proposal and nobody use it. I add the key `exports` for a better usage.

I publish my own version to give it a try and here is the result: https://github.com/atinux/nuxt-bcrypt-edge/pull/2

### CODE REVIEW

**Comment by bruceharrison1984** [comment]
- Can you bump the version to `1.0.0` since this is a somewhat breaking change
- Can you get the tests passing

Otherwise I understand and agree with the fix, LGTM.

**Comment by LeonHeidelbach** [comment]
Looking forward to seeing this fix merged in soon. @Barbapapazes thanks for taking the time to investigate.

**Comment by Barbapapazes** [comment]
I have update to `0.1.0` (since major<1, it's ok to do a breaking change) and I update the GitHub CI to have tests passing.

**Comment by LeonHeidelbach** [comment]
Very nice! @bruceharrison1984 is this ready to merge now?

**Pull request merged**
